name: radio_screen
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/image/
  fonts: 
    - family: Akrobat
      fonts:
        - asset: assets/fonts/Akrobat-Black.otf
        - asset: assets/fonts/Akrobat-Bold.otf
        - asset: assets/fonts/Akrobat-ExtraBold.otf
        - asset: assets/fonts/Akrobat-ExtraLight.otf
        - asset: assets/fonts/Akrobat-Light.otf
        - asset: assets/fonts/Akrobat-Regular.otf
        - asset: assets/fonts/Akrobat-Light.otf
        - asset: assets/fonts/Akrobat-SemiBold.otf
        - asset: assets/fonts/Akrobat-Thin.otf
  uses-material-design: true
  
  
